### ISSUE TITLE
Chameleon Projector renders you completely invisible

### ISSUE THREAD

**Issue by NuclearCreeperIII** [ScavStation/ScavStation#1029]
#### Description of issue
Chameleon projector renders you completely invisible and intangible when you dont scan an item

#### Difference between expected and actual behavior
Normally, the chameleon projector is meant to allow you to scan an item, and then disguise yourself as it. However, if you dont scan an item, it defaults to "nothing". This leaves you completely invisible and able to pass through other players, and you have no hitbox since its based on the sprite

That said, active camo as antag is extremely fun, so a more balanced item allowing full invisibility (but visible with thermals and no intangibility) would be wonderful

Also, I was unable to interact with doors or items in the world, or speak over comms (both through my headset and an active wall intercom) while cloaked, Im unsure if this is an intentional mechanic.

#### Steps to reproduce
Get a chameleon projector from the antag item shop
Dont scan an item
Use it

#### Length of time in which bug has been known to occur
First noticed 2024-06-22, last observed 2024-07-13

#### Client version, Server revision & Game ID
Unsure, I didnt document at the time. Most likely still present in current version of
Client Version: 514
Server Revision: 5ca1348f47d0cccb56bfecf5f79e15a965962a0a - main - 2024-07-18
07-13 Game ID cuG-cTFH

#### Issue bingo
- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
Closed due to being fixed upstream
