### ISSUE TITLE
cannot check bones while patient sits.

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#103]
#### Description of issue
I put a patient into a chair to check if she broke her legs falling down the elevator.  However, I had to unclip her from the chair to actually check, as I could not grab her at all while buckled to the chair.

#### Difference between expected and actual behavior
Unsure if working as intended.  Disregard if yes.

#### Steps to reproduce
Strap someone to a chair, grab their leg as you would if doing a manual check of skin and bone damage.

#### Specific information for locating

Find yourself a chair.  It can be anywhere on the ship.  Must be the type of chair you can actually sit in, though.

#### Length of time in which bug has been known to occur
Just found it out tonight because there was no power, so I couldn't check using the body scanner.

#### Client version, Server revision & Game ID
Not in game, dunno, m'dude.  That's not useful at all.  Current version as of 1/16/2020.  Also not useful.  But it'll probably still be around later on.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MistakeNot4892** [comment]
This is due to wheelchairs and grabs interacting weirdly and ending up with screwy pixel offsets. Will likely require an in-depth refactor of wheelchairs to get resolved.

**Comment by MistakeNot4892** [comment]
Moved upstream.
