### ISSUE TITLE
Avian clothes not being preserved between rounds

### ISSUE THREAD

**Issue by NuclearCreeperIII** [ScavStation/ScavStation#1030]
#### Description of issue
Intermittently, all clothing items in the "Avian" tab of the Equipment screen will be removed from your loadout between rounds. It doesn't happen between every round, but has been observed when the server restarted due to a map vote (clothing items were equipped in the pre-round, post reboot I spawned in without them). When I checked my character setup, they were no longer checked in my loadout. These are the only items being removed, the rest of my loadout remains intact.

#### Difference between expected and actual behavior
Equipment saved to your loadout should stay checked between rounds, but occasionally those found in the Avian tab do not.

#### Steps to reproduce
Unsure if it can be done reliably as it's an intermittent issue. My best recommendation is to make an avian character, join a round, then restart the server and rejoin the round as that character. It may not occur if you open character setup before spawning, but I'm unsure of that.

#### Length of time in which bug has been known to occur
Unsure, at least several months. This was an issue before the "all species can wear all clothings" update was added, and continued after it was removed. (in fact my complaints about that change were mostly due to this glitch, as it would randomly leave me with the ill-fitting uniform instead of my chosen clothes and id have to wait out the respawn timer to fix it.)

#### Client version, Server revision & Game ID
Client Version: 514
Server Revision: 5ca1348f47d0cccb56bfecf5f79e15a965962a0a - main - 2024-07-18 (unless its changed since last night, this is todays version)
Game ID: cuK-c6lG

#### Issue bingo
- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Alceris** [comment]
You can tick the 'could be reproduced by different players' checkbox, and I have more details: This happens whenever you already have the character selected when the server restarts, and reloading the character slot gets your item selection back.

**Comment by Qumefox** [comment]
Closed due to being fixed upstream
