### ISSUE TITLE
Away missions are locked to human and yinglet

### ISSUE THREAD

**Issue by NuclearCreeperIII** [ScavStation/ScavStation#1036]
#### Description of issue
Away missions are locked to human and yinglet, other species cannot join as colonist, merchant, etc

#### Difference between expected and actual behavior
Ideally, would like to be able to play away mission roles with any species that you can join crew as (and maybe other species as well, if any context isnt unreasonable have access to Vox it'd be crashed pod)
Instead, its hard-locked to human and yinglet only

#### Steps to reproduce
Join game as a species other than human or yinglet (observed with Avian and Skrell)
Away Mission spawns are listed as unavailable on both the join screen and the skill setup screen

#### Length of time in which bug has been known to occur
As long as I can remember

#### Client version, Server revision & Game ID
Away missions are locked to human and yinglet, other species cannot join as colonist, merchant, etc

#### Issue bingo
- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
It is. While you did your part originally. I never noticed I needed to make changes on scav as well. I reopened this so I wouldn't forget...again.  I just haven't made it back around to touching scav yet

**Comment by Qumefox** [comment]
https://github.com/ScavStation/ScavStation/pull/1097
