### ISSUE TITLE
Trashbag pulls parts out of airlock

### ISSUE THREAD

**Issue by MrBriggs18** [ScavStation/ScavStation#1041]
#### Description of issue

Clicking hatches with a trash bag produces a secure airlock electronic out of them and into the trash bag. Said object then returns to user's hand/trash bag whenever the hatch is clicked again, no matter how far away it is thrown (including being spaced). Hatches are in assembled state during interaction (no screwdriver, wrench, etc applied beforehand). Destruction of secure airlock electronic prevents its reappearance, subsequent attempt to press trash bag on the hatch that had its electronic destroyed produces a fire door electronic out of it, however it does not return to users hand on further clicks. Hatch remains functional the entire time.

#### Difference between expected and actual behavior

I don't think you're supposed to pull out parts out of the closed airlock just like that. 

#### Steps to reproduce

Take trash bag in hand -> click the door.

#### Specific information for locating

Any hatch will do, it seems.

#### Length of time in which bug has been known to occur

I have first discovered it at 21.07.2024 and persists at 26.07.2024 (+- day for timezones).

#### Client version, Server revision & Game ID

I can NOT copy this string of crap for some reason, but it's present on both main maps.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
Closed due to being fixed upstream
