### ISSUE TITLE
cannot bite or kick anyone if hands amputated while handcuffed

### ISSUE THREAD

**Issue by sharah-za-fluffy** [ScavStation/ScavStation#1042]
#### Description of issue
see title

#### Difference between expected and actual behavior
I should be still able to bite people after they go all Leopold II on my ass 

#### Steps to reproduce
be annoying enough to be both handcuffed and have your hands cut off while they forgot to remove cuffs when doing so
switch attack to bite and attempt to bite

#### Length of time in which bug has been known to occur

last week or two I forget exactly the round where I landed shuttle in bar 

#### Client version, Server revision & Game ID

Date
2024-07-27
Branch
main
Game ID
cuU-aDFO
Runtime Version
514.1589
Compiler Version
514.1589
Revision
29922fe6daafc136b73ee608b0a8399042ea7b11

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
Closed due to being fixed upstream
