### ISSUE TITLE
Anchoring chairs issue

### ISSUE THREAD

**Issue by LuchiousCaine** [ScavStation/ScavStation#1046]
#### Description of issue
Nuclear noticed some anchoring issue with chairs and I went in to reproduce.
Sure enough, every single chair/sofa, when using wrench on it, says "You anchored the [chair]", when in fact you just unanchored it.
Reverse is also the case, where it says you disanchored it when you actually anchor it.
Anchoring is also instant for them, but I don't remember if that was always the case?
I also checked if lockers and machines have this issue, but no, they function as normal, with a timed wrenching to anchor, so it seems to be chair specific.

#### Difference between expected and actual behavior
For the action to describe that you anchor when anchoring and vice versa.

#### Steps to reproduce
Have a wrench and use on any chair to anchor/disanchor.

#### Specific information for locating

n/a

#### Length of time in which bug has been known to occur

Found 26th July.

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 29922fe6daafc136b73ee608b0a8399042ea7b11 - main - 2024-07-27
Game ID: cuU-a9Yl
Current map: Tradepost Mollusc

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
Closed due to being fixed upstream
