### ISSUE TITLE
pickaxes and sledge hammers with towercap heads can remvoe steel cladding from walls

### ISSUE THREAD

**Issue by sharah-za-fluffy** [ScavStation/ScavStation#1047]
#### Description of issue
it's a might bit funny a purely wooden tool can take apart steel walls, personally I don't mind, but this can be a problem for others, esp more serious servers where you don't want people to be sneaky little shits and make secret doors everywhere with just a bit of towercap harvest

#### Difference between expected and actual behavior
I should maybe have to use steel or at least iron as the head of my tool and not be a lazy cheapass that can just use a all wood tool like it's the first day of a minecraft save

#### Steps to reproduce
grow tower cap
harvest it
chop logs into planks
make tool handle and pickaxe head or sledge hammer head
use on wall

#### Specific information for locating

pick axe sledge hammer 

#### Length of time in which bug has been known to occur

since the ability to craft said tools where added 

#### Client version, Server revision & Game ID

Date
2024-07-27
Branch
main
Game ID
cuU-dEcu
Runtime Version
514.1589
Compiler Version
514.1589
Revision
29922fe6daafc136b73ee608b0a8399042ea7b11

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
Closed due to being fixed upstream
