### ISSUE TITLE
Random Events Seemingly Disabled

### ISSUE THREAD

**Issue by Cegmeister** [ScavStation/ScavStation#1048]
#### Description of issue

Random events seem to be disabled by default, which means alerts tend to not happen unless an admin enables them during a round. This means no drone revolts, no biological hazards, no pipe explosions, no clogged drains, and no carp swarms.

#### Difference between expected and actual behavior

These events should happen regularly during a round. As of now, they do not and the round is _dreadfully_ peaceful.

#### Steps to reproduce

Join on an ongoing round, or a new round, and play for an extended period of time. Eventually you will notice a lack of alerts. Best to do it on a less populated round where an admin has not manually enabled events.

#### Specific information for locating

N/A, affects the whole round. If there is a configuration file then I apologize for not knowing the name.

#### Length of time in which bug has been known to occur

Upwards to a month or two.

#### Client version, Server revision & Game ID

Revision: ScavStation
Date
2024-07-27
Branch
main
Game ID
cuU-dEcu
Runtime Version
514.1589
Compiler Version
514.1589
Revision
29922fe6daafc136b73ee608b0a8399042ea7b11

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
Fixed by config tweaks apparently
