### ISSUE TITLE
Entering exosuit from wheelchair locks your 'exit' position to the wheelchair

### ISSUE THREAD

**Issue by Mairujyat** [ScavStation/ScavStation#1051]
Playing a wheelchair-bound character has some quirks where exosuits are involved.
Entering the exosuit works as normal. Exiting it at any point will warp you to the wheelchair, however.

I suspect the same result might come about if entering an exosuit from another 'ridable' vehicle, such as a space bike or segway. I have yet to test this.

**Comment by Qumefox** [comment]
Fixed upstream. Closing
