### ISSUE TITLE
Hyposprays spawned as part of loadout cannot be emptied into containers

### ISSUE THREAD

**Issue by NuclearCreeperIII** [ScavStation/ScavStation#1059]
#### Description of issue
Hyposprays spawned as part of loadout cannot be emptied into containers

#### Difference between expected and actual behavior
Normally, hyposprays can be filled from a bottle by clicking on the hypo with the bottle in hand, and vice versa: they can be emptied into a container by clicking on the bottle with the hypo in hand.
However, if you spawn with a hypospray as part of your loadout (e.g. with the medical director role), they can be filled from a bottle, but they cannot be emptied into bottles. The only way to remove chems from the hypospray is to inject it, which isnt viable for most drugs in most scenarios.

#### Steps to reproduce
-Spawn as Medical Director
-Put water (or another chem) in a beaker
-Click on the hypospray with the beaker. you can see that it transfers fluid
-Click on the beaker with the hypospray. there is no response
-Get the hypospray mapped into ministation's medical director's office locker
-Repeat the previous two steps. observe that you are able to transfer the chem back from the hypospray into the beaker

#### Length of time in which bug has been known to occur
I vaguely remember noticing some inconsistent behavior with emptying hyposprays that may have been caused by this bug a while back, but this is the first time I know for a fact that the bad hypospray was the one spawned in with by a medical director.

#### Client version, Server revision & Game ID
Client Version: 514
Server Revision: cd52d9ef96bc9a783488c509caea52bb66565b24 - main - 2024-08-10
Game ID: cu8-aCU9

#### Issue bingo
- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
Fixed upstream. Closing
