### ISSUE TITLE
cargo and enclave airlocks do not cycle properly (mollusc station) 

### ISSUE THREAD

**Issue by sharah-za-fluffy** [ScavStation/ScavStation#1072]
#### Description of issue
cargo and enclave airlocks do not properly close behind you when you cycle it to the outside and thus promptly vent those departments

#### Difference between expected and actual behavior
not letting the air out when I go mining

#### Steps to reproduce
attempt to use airlock, watch for the back door, and resist urge to call idiot other players slurs when they say this has been a known problem for a while yet you see no tickets about it already made.

#### Specific information for locating

airlock leading to outside smelter area in mollosc station's cargo department

#### Length of time in which bug has been known to occur

apparently awhile now but lmao writing tickets am I right

#### Client version, Server revision & Game ID

Date
2024-08-30
Branch
main
Game ID
cvs-dFbE
Runtime Version
514.1589
Compiler Version
514.1589
Revision
8b3f2776b67f8d1dde4137190ff35b4befad9c46

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
fixed by https://github.com/ScavStation/ScavStation/pull/1073#issue-2498620625 i believe
