### ISSUE TITLE
Double-Clicking in PDA Window Crashes Game

### ISSUE THREAD

**Issue by nodesc** [ScavStation/ScavStation#1076]
#### Description of issue

Opening a PDA window and clicking repeatedly within it will crash the game.

#### Difference between expected and actual behavior

Reasonably, a crash should not happen.

#### Steps to reproduce

How it happened for me:
1) Get an email
2) Open email in PDA
3) Click repeatedly in window (on text to select maybe, which is what I was doing)
4) Crash

If it means anything, I was clicking on an image link but it didn't appear to be a working link, rather one to just copy and paste.

#### Specific information for locating

PDA
Email Client

#### Length of time in which bug has been known to occur

September 6th, 2024

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 98da735ee218122494dca09953264db5bb72802a - main - 2024-09-05
Game ID: cvy-aNJk
Current map: Tradepost Mollusc

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
Closing due to this being BYOND and not neb/scav code related
