### ISSUE TITLE
Solar panels do not work

### ISSUE THREAD

**Issue by Typhin** [ScavStation/ScavStation#1108]
#### Description of issue
Solar panels do not provide power - Tracker shows sun at 0 deg North, panels at 0 deg North, generating 0 power.

Not a display issue, SMES units also do not receive power.

#### Difference between expected and actual behavior
Solar panels should be able to generate power.  Sun should be at some position that the tracker can follow.

#### Steps to reproduce
Wire solars, check console.  It will show sun at 0 deg (north), panels at same, no power generating.

#### Length of time in which bug has been known to occur

Beginning after update to dev branch on Saturday Nov 9, 2024.

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 1976ade77218700d626522073d596d9963f5b37b - dev - 2024-11-09
Game ID: cwB-dLzo
Current map: Tradepost Mollusc

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
fixed with #1116
