### ISSUE TITLE
Wallet does not accept items

### ISSUE THREAD

**Issue by Typhin** [ScavStation/ScavStation#1109]
#### Description of issue
Wallet (normal/painted) does not accept items such as ID card, ID papers, Credits, or Grooming Tool (hairbrush).
There is no error given, it simply does not work.  Wallet can be alt-clicked and "Open Storage" selected, but items cannot be placed into storage.

#### Difference between expected and actual behavior
Wallet should be a container with the ability to hold the above items, or a "[container] cannot hold the [item]" style error should be printed if it cannot.  Wallet previously held all these items.

#### Steps to reproduce
Attempt to place item into wallet.  Nothing happens.

#### Specific information for locating

Wallet is now "Wallet (painted)", there is no message on attempt to insert item.

#### Length of time in which bug has been known to occur

Since switch to dev branch on Saturday Nov 9, 2024.

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 1976ade77218700d626522073d596d9963f5b37b - dev - 2024-11-09
Game ID: cwB-dLzo
Current map: Tradepost Mollusc

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
verified fixed
