### ISSUE TITLE
Add a shared crew yinglet hoarding goal.

### ISSUE THREAD

**Issue by MadCowKastor** [ScavStation/ScavStation#148]
See if it's possible (easy enough) to have a unique container on the map that a goal checks for how much money is in it.
Why, communal gather money (and clams) and put them in the Enclave treasury box goal for yinglets.
Oppose with a captain role to also gather money, if the numbers are right this should only cause antagonism in lean times.

Note: most active players don't seem to care much about standard goals, it's having a tracker for in case you DO want to add to the ying-hoard that's important.

**Comment by SodiumShine** [comment]
Should it be specifically cash, or certain items of worth? Like "Collect $1,000 thals worth of shinies" and include a list somewhere of what shinies means. e.g. jewellery, circuit boards, diamonds, etc

**Comment by MadCowKastor** [comment]
Cash seemed easiest which is why I recommended it. But if you can work out how to implement your idea well that'd probably be better.
