### ISSUE TITLE
Bombhatch trap door

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#160]
'Would it be possible to have fake sliding floors like we have walls?'
 hmmm you could maybe make a fake floor that is actually a structure
and screwdriver to unanchor, or such
you couldn't do it the way walls do it, with the turf var, because open space requires a specific turf type
so if they right-clicked the turf they'd see 'open space' and 'steel floor' listed
'Could you hook it up to a console to make a multi-level pitfall trap?'
'That sounds more like a floor hatch/airlock than a fakewall'
'... which is an interesting concept'

**Comment by SodiumShine** [comment]
@TheKnightofAura please provide more details/clarification to the feature request.

**Comment by TheKnightofAura** [comment]
This was mostly a reminder for Six, since I just copied our convo from the time to the issue report

**Comment by MistakeNot4892** [comment]
This got moved up to Nebula FRs.
