### ISSUE TITLE
Random mob teleportation while drunk

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#162]
#### Description of issue
I was stumbling around drunk last night and I kept teleporting back to stairs after sobering up some.

#### Difference between expected and actual behavior
Teleporting is fucky and fucky is banned

#### Steps to reproduce
Unsure.  Get drunk and stumble up and down stairs and then walk away for a while.   You MIGHT JUST teleport back to them, or back into their area?

#### Specific information for locating

Stairs beween lowest floor, mid floor, and upper floor in cargo.  Unsure which stairs I spawned by or if it repeated in the same spot.  Sorry!

#### Length of time in which bug has been known to occur

Since 1/19/20.  This was the first and only instance I had.

#### Issue bingo

- [x ] Issue could be reproduced at least once ---- Happened twice in one game, drunk both times (different instances of being drunk, she sobered up between instances)
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by zacklucky7** [comment]
This happened to me on the round that ended approximately 11:30 PM EST. Shortly after I joined, I was standing on the catwalk where the merchant teleport terminal is. Aura KNIGHT called the lift, and after the sound played, I suddenly found myself in the underside level beside the stairs. I posted in OOC when that happened. If it helps, I believe I said _**WAT**_.

I was not drinking when it happened. This is the first instance I ran into it -- 1/20 approximately 9:30 PM EST (may have been 8:30 PM EST)

**Comment by AcidFluxRaims** [comment]
This was also happening to me all yesterday evening when I was playing. You definitely don't have to be drunk to have it happen, just moving across Z-levels. It can take up to a full minute before it affects you as well, so you can be in a room doing whatever you needed to do, and then you'll find yourself at the stairwell again randomly.

**Comment by AcidFluxRaims** [comment]
Alllllssssooooooo went out EVA last night and managed to get teleported to the screen that also has the navigation sector map, with no way to get back to the ship. Went out of the rear lower airlock and got about 2 tiles away from the aft of the ship, still very much within visual range.

**Comment by zacklucky7** [comment]
Happened to me again -- relevant info to my knowledge:

1. I was near the staircase on the second floor
2. I teleported down to the first floor shortly after climbing up
3. I moved around a little and then teleported back to the first floor stairs

One piece of data that *might* be useful:

After my second teleport, I was right beside Aura KNIGHT. I was looking for them to use the Give verb to give them an item. When I tried, I got the error that basically means 'this person isn't here anymore' (I can get an exact error next time it happens) even though I was right beside them

**Comment by zacklucky7** [comment]
I noticed that I *always* seem to teleport to the same place on the stairs:

![image](https://user-images.githubusercontent.com/46574814/73512564-16930a00-43b8-11ea-90bd-512797d1efec.png)

**Comment by ZirconiumWit** [comment]
seconded, I'd noted that it was the stairs but yeah it's definitely always the same SPOT on the stairs.  Such a weirdo bug

**Comment by MistakeNot4892** [comment]
Going to bump this up to Nebula since it is more than likely a problem on the reinstated Bearcat as well.
