### ISSUE TITLE
yingfatigue feature request

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#171]
#### Description of issue
Mega low priority eventual possible feature:
Yinglet fatigue.  They get tired more quickly and eat more frequently than humans.  Dunno how much of a pain this is to code.  I imagine since it's something I'm looking for, it's not going to be easy.  So feel free to disregard!

#### Difference between expected and actual behavior

Expected:  Yinglets are hyperactive bundles of finite energy
Actual: Yinglets are hyperactive bundles of eternal energy until they die which is often

#### Steps to reproduce

Become the scav.  You'll see!  

#### Specific information for locating

I think that their energy comes from the heart and brain.

#### Length of time in which bug has been known to occur

Ying energy is eternal.  Until now, that is!

#### Client version, Server revision & Game ID

All versions predating 1/21/2020

#### Issue bingo

- [X ] Issue could be reproduced at least once
- [X ] Issue could be reproduced by different players
- [X ] Issue could be reproduced in multiple rounds
- [X ] Issue happened in a recent (less than 7 days ago) round
- [X ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by SodiumShine** [comment]
@ZirconiumWit can you provide more specific details and clarification?

**Comment by MistakeNot4892** [comment]
Yinglets currently metabolize 25% faster than humans, and there's no equivalent mechanic for fatigue other than stamina. May add a stamina mod down the track but closing this for now.
