### ISSUE TITLE
Enclave Patriarch does not have access to exosuit fabricator

### ISSUE THREAD

**Issue by zacklucky7** [ScavStation/ScavStation#198]
#### Description of issue

The Enclave Patriarch does not have ID access to the exosuit fabricator.

#### Difference between expected and actual behavior

The Patriarch can use all the lab equipment *except* the exosuit fabricator!

#### Steps to reproduce

1. Spawn as Enclave Patriarch.
2. Try to use exosuit fabricatior.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MistakeNot4892** [comment]
Fixed in  #285

**Comment by MistakeNot4892** [comment]
@SodiumShine corrected me

**Comment by SodiumShine** [comment]
Need to hash out what patriarchs should and shouldn't have, and the enclave dynamic and such with ivenmoth

**Comment by MistakeNot4892** [comment]
Exosut fabricators no longer exist and the current set of fabricators are all unrestricted, no longer an issue.
