### ISSUE TITLE
MEDpatch can be seen through z levels.

### ISSUE THREAD

**Issue by SodiumShine** [ScavStation/ScavStation#212]
Witnessed Dr. Dessi roaming around the lower cargo bay while haunting the upper cargo bay. MEDpatch was visible through all turfs.  No other portion of Dr. Dessi was visible.

This issue is not new, just forgot to write it down until now.

**Comment by MistakeNot4892** [comment]
This is due to effects that layer over the lighting engine setting plane directly. Noooot sure if this is fixable. Will have a think with my brain.

**Comment by MistakeNot4892** [comment]
Moved to upstream.
