### ISSUE TITLE
Removed organs remain visible as screen items on the donor's screen.

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#216]
#### Description of issue
Dear people resources,

Today, I operated on the very honorable Matriarch, Sharah for a liver transplant due to hepatic necrosis.  It went splendidly until I accidentally cracked her spine trying to use a hemostat to attach the new prosthetic liver.  Needless to say, all such mishaps were a complete breeze to repair.  Medical malpractice notwithstanding, I absentmindedly put her rotten liver in my pocket to keep another yinglet from eating it.  I had intention to sell it to merchants abroad.   I never got around to it, to be honest.  

Now, here's the weird thing.  Sharah could see her liver in the spot [on the screen] where it was in my bag.  If I removed the liver and put it in my pocket, she could have SWORN that there was a bloody disembodied liver in her pocket.  Wherever I put the liver, she could see it there until I dropped it.  If I picked it up again later, she could still see it.  I've never seen a situation like this!  

I believe this to be a case of haunting.  Could you send a team of specialized specter hunters to remove these phantoms from the liver, and possibly other organs?  And also, maybe implement annual medical primers/trainings.  My mistakes were pretty unforgivable in there.

#### Difference between expected and actual behavior
One would expect a doctor to perform better, and one would expect that one's patient would not sit there and be able to see where you have their liver on your person.  

#### Steps to reproduce
All I know is I took her liver, threw it across the room, retrieved it when someone claimed they intended to eat it, and put it in my pocket.  

#### Specific information for locating

I know you're people resources and medicine isn't your wheelhouse, but the liver is in the abdomen.  Please send trained medics to run tests.  Don't do this yourselves.

#### Length of time in which bug has been known to occur 

 Today only

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MistakeNot4892** [comment]
Moved to upstream.
