### ISSUE TITLE
Near sightedness not hindering enough

### ISSUE THREAD

**Issue by SodiumShine** [ScavStation/ScavStation#288]
Too easy to see forever without my glasses. Not having them on only makes everything very slightly darker.

Distant things should be near impossible to discern, or at least too dark to see.

![image](https://user-images.githubusercontent.com/4461697/73713699-7136b800-4762-11ea-9893-e252bc439664.png)
![image](https://user-images.githubusercontent.com/4461697/73713704-785dc600-4762-11ea-99c1-7efc3a5da6b7.png)

**Comment by MistakeNot4892** [comment]
This is a bug with the scaling system I think, will look into it.

**Comment by MistakeNot4892** [comment]
Moved upstream.
