### ISSUE TITLE
feature request - newsprinting feed

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#293]
#### Description of issue
Newsfeeder is the issue.  Too advanced!  Too sciencey.  It's time to go to paper.  A newsfeeder can be added to various departments throughout the ship which will automatically print out an up-to-date newspaper so everyone can remain informed of all the (un)important stuff going on in the world.  And if you try to read the news with harm intent and crumple it up, no problem.  Just push a button on the feeder and it'll print another copy of the current edition.

#### Difference between expected and actual behavior
Actual behavior - newsfeeder doesn't produce garbage, so it's easy to ignore
Expected behavior - newsfeeder will not be ignored.

#### Steps to reproduce
hhnnnnn

#### Specific information for locating

at a local newsprinting feed near you

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MistakeNot4892** [comment]
How does the newscaster paper printing function differ from this?

**Comment by SodiumShine** [comment]
@ZirconiumWit i feel like this was discussed in chat but i don't remember

**Comment by MistakeNot4892** [comment]
Unsure if this was different to newcaster printing or not, can't remember the convo. Could just be a newsprinter resprite if someone ends up making one. Can revisit then.
