### ISSUE TITLE
Codex entries do not reflect correct fusion temperatures

### ISSUE THREAD

**Issue by SodiumShine** [ScavStation/ScavStation#302]
Duet-Trit and Duet-Duet both claim a fusion temperature of 100 Kelvin, not including T0C, leading to confusion. Codex entry should either show a value of (Fusion Temperature + T0C) or show in the codex that T0C is not included in that value.

**Comment by MistakeNot4892** [comment]
Fusion torus uses +T0C as well so codex should be updated.

**Comment by SodiumShine** [comment]
> In the process of deuterium-tritium fusion, /material/gas/helium is produced. 

Paths showing up in codex also woops

**Comment by MistakeNot4892** [comment]
Still needs T0C update for codex temperatures.
