### ISSUE TITLE
After out of body experience (Brain transfer bug)

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#315]
TL;DR Did a lot of surgury work. Sucessfully put a scav in an AI. He didn't like it, found it boring, wanted back. Putting him back didn't work so well. Did all the steps, (even though there was some severe oddities, re-attached his brain sucessfully, but he did not regain control of the perfectly healthy body.
I know for a fact it was attached, as I had to cut his brain out again to put it back in the MMI, and he was still alive for that.

**Comment by MistakeNot4892** [comment]
The bug here is pulse not resetting on death - removing the brain kills the body, the pulse just doesn't seem to get the memo.
