### ISSUE TITLE
Atmospherics machinery is unreliable

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#333]
EDIT by Six.
- Helium is moving from the engineering connectors into the pipeline, but is not passing the omni-mixer to the injector pipes.
- Even when piped directly to the injector, helium is not entering the fusion chamber ('the reinforced turf has no gasses').
- When examined the pipes claim they are not receiving power.

Mairu also notes the injector in Atmospherics itself is not working.

**Comment by MistakeNot4892** [comment]
Moved to upstream.
