### ISSUE TITLE
Bug-like behavour: Chemmaster chem storage

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#336]
The chemmaster has a buffer that it uses for taking specific things from the beaker, and putting into pills. Anything in the buffer when you take out the beaker is lost forever.

Which makes it feel rather strange when you directly pour chems into the chemmaster, filling up the buffer, with no beaker put in. Not only can you not access the buffer to make pills from what you pour in, but it will still be purged if you put in and take out a beaker. This is especially odd considering the chemmaster has a specific function to destroy chems from a lot. Perhaps it should simply have a limited internal size, and allow chem manipulation without a beaker?

**Comment by MistakeNot4892** [comment]
So - reagent transfer behavior is due to the chem master having the open container flag, which seems to be deliberate. Removing the flag stops internal reagent transfer. Going to see if I can let you mess with reagents without a beaker, but if I can't I'm marking this down as not a bug.

**Comment by MistakeNot4892** [comment]
Migrated upstream as it affects the main codebase.
