### ISSUE TITLE
Stranded Survivor On Job List At Join, Not Able To Be Chosen

### ISSUE THREAD

**Issue by CheeseDogg0** [ScavStation/ScavStation#337]
Stranded Survivor shows up as a possible job at join/roundstart but is not selectable. Its possible to set skills for Stranded Survivor and other "stranded" type jobs, but you can never be the job during a round. Either remove it or make it available, it's too tempting.
#### Difference between expected and actual behavior

Job should be selectable, as other jobs are. It is not.

#### Steps to reproduce

Try and select Stranded Survivor.

#### Specific information for locating

Joblist at join.

#### Length of time in which bug has been known to occur

As far as I know, the duration of the server.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by SodiumShine** [comment]
I think it should be removed. I'm not sure what being a stranded survivor brings to a round, but it sounds to me like it just splits up the potential crew.

**Comment by MistakeNot4892** [comment]
Moved to upstream.
