### ISSUE TITLE
Baxxid player icons don't reflect gibbing properly

### ISSUE THREAD

**Issue by SodiumShine** [ScavStation/ScavStation#341]
![image](https://user-images.githubusercontent.com/4461697/74095015-b1b97b80-4b3e-11ea-820a-21a7919b21cf.png)

>  This is   Unknown, a Baxxid!
> They aren't responding to anything around them and seems to be unconscious.
> They do not appear to be breathing.
> They are missing their upper body.
> They are missing their lower body.
> They are missing their head.
> They are missing their left arm.
> They are missing their right arm.
> They are missing their left leg.
> They are missing their right leg.
> They are missing their left hand.
> They are missing their right hand.
> They are missing their left foot.
> They are missing their right foot.

This job performed by ore processor

**Comment by MistakeNot4892** [comment]
Likely due to markings not being applied properly.

**Comment by SodiumShine** [comment]
A bug with markings or that i was missing some? I'm fairly sure i had all of them applied.

**Comment by MistakeNot4892** [comment]
Bug with markings, not your fault.

**Comment by MistakeNot4892** [comment]
Appears to have been resolved.
