### ISSUE TITLE
Reagent scanner for Doctors or Chemists

### ISSUE THREAD

**Issue by CheeseDogg0** [ScavStation/ScavStation#343]
#### Description of issue
Currently the only way to tell whats in something is to put it into the Chemmaster/Chemical dispenser. I feel like med-crew should have a handheld reagent scanner or a reagent scanner built into their pda. Having a single scanner in chem might be the better option, as it limits the amount on the map. Being able to draw blood and scan it for bad stuff would be very helpful, and quicker with a handheld scanner than running it to chem to check it. In the future, It might be a better idea to have a centrifuge for this purpose, as I believe that is what real Labs do for blood-work.
Maybe make Chem into Med-lab for these kinds of things...

**Comment by TheKnightofAura** [comment]
As a note, besides seeing what's inside blood, if you're a really good chemist, you can see what chemicals are in something, as well as the total ammount of things in a thing. I do agree a way to check without disassembly would be nice

**Comment by SodiumShine** [comment]
If we're going to do this I'd prefer a single scanner rather than PDA scanner, for Tradeship purposes. However, I'm personally unsure if I like the idea at all, as I prefer equipment that you can't just take everywhere with you.

**Comment by MistakeNot4892** [comment]
I think I am going to close this one as it's a bit iffy on whether or not a reagent scanner is needed, and would be very trivial to map in if desired.
