### ISSUE TITLE
Alchemical itemic creations

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#352]
Note: all of these are intended to be temporary in durations. 2-5 minutes.

- Tanglefoot bag: Tossable. On hit force-occupies slot, and heavily slows, requiring channel to remove
- Liquid Blade: On it's own, forms weapon when used. If combined with reagents first, applies reagents on hit
- Shard Gel: simple grenade that shatters into caltrops over small area, embeds a caltrop on impact
- Itching powder: Causes you to drop items, so you can scratch itch
- sneezing powder: Causes you to randomly activate held items, (Shoot gun, spray bottle, dump bucket)
- Instant Airslime: Engulfs head in breathable bubble of liquid oxygen, providing short term emergency breathing, with no tank
- Blackblood: makes blood black, (no DNA/type?) prevents bleeding for active duration
- Impact foam: softens fall damage when you land on it
- Alchemical Glue: Temporary door welding, glueing things to floor/surface, or sticking people to people
- Ethereal Grease: like space lube, but it evaporates after it causes a single slip, or slide.

**Comment by MistakeNot4892** [comment]
Very unlikely to get implemented in the short term - going to close for now.
