### ISSUE TITLE
feature request - illicit archives

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#354]
#### Description of issue
traitors should gain access to the 'illicit archives' wherein all academic texts are kept.  Possible new traitor objectives : upload texts to the illicit archives, including crew dossiers and medical files.  This is a placeholder for a more fleshed out idea as more thoughts come to mind, but I'll forget if I don't post this now

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by SodiumShine** [comment]
I like this idea and want to do it but it's also low priority on my list, so either someone else can do it or I can get to it later.

**Comment by ZirconiumWit** [comment]
Not a priority at all, posted per your request

**Comment by MistakeNot4892** [comment]
More or less not actionable as-is, and Zirc and Winter have both moved on, so closing for now.
