### ISSUE TITLE
Elevator is silent

### ISSUE THREAD

**Issue by eggbread-sudo** [ScavStation/ScavStation#366]
#### Description of issue
just happened for me yesterday feb 10. 
ambient sounds stop when stepping onto the elevator

could it be trying to play ambient sounds from the wrong floor? just a guess, no idea..
#### Difference between expected and actual behavior

Sounds of current floor should persist when entering elevator area, but any playing sounds will stop on entering the elevator, new sounds can occur

#### Steps to reproduce
enter elevator from second floor  just outside saloon.. I have not tested extensively but it definitely happens here.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
````
re: elevator - sounds will always cut off when crossing areas, areas have different ambience. The hissing sound that you get in the main room won't be present on the elevator as the elevator has no vents.
````

**Comment by SodiumShine** [comment]
Linking to #248 for reference.
