### ISSUE TITLE
UI is fuckled at 96x96 and beyond

### ISSUE THREAD

**Issue by eggbread-sudo** [ScavStation/ScavStation#367]
#### Description of issue
UI buttons start to overlap and go off the edge of the screen when game is zoomed in. (forgot the specific term the game uses instead of being zoomed in whatever)

UI goes towards the right side of the screen leaving space at the left. 

seems like maybe the game isn't expecting a wide screen monitor? 

#### Difference between expected and actual behavior

UI buttons should stay proportionally in place on the viewable area regardless of scale

#### Steps to reproduce

1) use my computer (apparently)
2) set scale/zoom at 96x96 or higher
3) gather fruits of thine labor and weep

#### Specific information for locating

apparently this is an issue that's fixed for most people, but not me. a similar issue persists with the elevator sound scape... should I reinstall beyond?

#### Length of time in which bug has been known to occur

been happening since I started playing the game a  month or so ago

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
This seems to happen for anyone using a widescreen monitor. Will try to add some debugging verbs to chase it down.

**Comment by MistakeNot4892** [comment]
Should be fixed mostly by #380.

Keep in mind, UI elements overlapping isn't a bug, it's a consequence of trying to use an icon size that is too big for your screen resolution.
