### ISSUE TITLE
Lag spike in saloon

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#387]
#### Description of issue
Dear People Resources,
I haven't written in a while.  Sorry.  I do know how you enjoy hearing feedback from employees.

I was working a recent shift, and found a temporal anomaly.  This strangeness was located at the hatch nearest to the medbay leading into the saloon.  You'd just be walking along and suddenly you'd freeze, and time would stop but just for you.  People would talk, but you might not see them moving while you're caught in the anomaly.  ANd you'd be caught for six - ten seconds.  When you leave the anomaly, everything you did while inside the anomaly happens, and I'd typically find myself on the other side of the saloon, confused as to how I'd gotten there.  Imagine what a nightmare this would be if you were in the middle of resolving a conflict, or were fleeing from something terrible!  This happened to me three times in one shift.  I think perhaps a spy left this anomaly there to protect the public.  I say this because for the duration of this shift I was a changeling, which I think is a serious problem.  People shouldn't just WAKE UP and be a whole new species.  What kind of weird research are you people doing on us here?  

Anyway.  I don't know if the anomaly would trigger for someone who ISN'T a changeling.  I furthermore do not know if the anomaly was restricted to just the one round.  What I'm saying is, I wouldn't mind waking up with such power again.  Please consider this not as a request, but simply as an observation.  

#### Difference between expected and actual behavior
When you walk through doors, time does not usually just stop.  You don't normally just phase-shift to the other side of a room you've just entered, either.

#### Steps to reproduce
Enter saloon through the door closest to chemistry/medbay.

#### Specific information for locating

I wish I knew!  Try walking in to the saloon through the medbay side hatch.  If that doesn't do it, try being a changeling?  

#### Length of time in which bug has been known to occur

Just 2/14/2020

#### Client version, Server revision & Game ID

Definitely the version just prior to becoming our own repo.  Grats, by the way.  You've gone from being a fork to having a silver spoon.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
This is a map/BYOND client issue - similar issues on Bay for many years with no clear fix. May need a 'cantfix' tag for this.

**Comment by afterthought2** [comment]
Noting that I've fixed a few client-lag issues of this general type. The typical problem is failure to `Cut()` overlays, and then adding overlays in `update_icon` repeatedly. `overlays` does not follow typical byond list operation rules, and so this can result in progressively slower rendering by all clients in view.

If that's what is happening here, would be helpful to know which obj is responsible.

**Comment by MistakeNot4892** [comment]
This seems to be less prevalent (along with the weird stairwell glitches) on the new host and with more things using SSoverlays (also human icons are a lot less laissez faire about null icon states, which might be helping). Going to close it for now, can reopen if it starts happening again.
