### ISSUE TITLE
[FR] Craftable shields

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#397]
An important step in defence, especially in a setting where projectiles are so widespread, shields are already in the game, and they function! Though, I am not sure HOW they function, or the numbers behind the screen, I DO know I have blocked blows with them, and thus, they are useful despite taking up a hand slot. We have craft-able armour, capable of being made of most any material, I simply ask for the same of shields.

**Comment by MistakeNot4892** [comment]
Discussing this upstream but as-is shields only currently block hits entirely rather than providing armour. Could just add a recipe to craft metal/plasteel shields, plastic shields, etc. easily enough, but something equivalent to the craftable armour isn't feasible currently.

**Comment by MistakeNot4892** [comment]
Implementing upstream https://github.com/NebulaSS13/Nebula/pull/2352
