### ISSUE TITLE
baxxid arm stuff

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#408]
#### Description of issue
can't give full description, not my issue.  but baxxid arms don't stab spiderlings OR be used to write on a deck.

#### Difference between expected and actual behavior
baxxid arms might be treated as weapons wrt spiderlings.

#### Steps to reproduce
be baxxid, stab spider, write graffiti on deck or wall

#### Specific information for locating

in the arms of baxxid

#### Length of time in which bug has been known to occur

dunno.  Today, I guess.  Probably as long as there have been baxxid

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Their arms are just big beefy hands, this isn't a bug technically (though the baxxid are).
