### ISSUE TITLE
can't wear buckets on head

### ISSUE THREAD

**Issue by eggbread-sudo** [ScavStation/ScavStation#412]
#### Description of issue

I have bukkit, it not do a hat

#### Difference between expected and actual behavior

pls

#### Steps to reproduce

hat

#### Specific information for locating

bukkit for my yinghead

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Testing webhook, ignore

**Comment by MistakeNot4892** [comment]
Testing webhook, ignore

**Comment by MistakeNot4892** [comment]
Merged on Neb, will hit Scav next update.
