### ISSUE TITLE
Burn Pills Named Kelotane

### ISSUE THREAD

**Issue by CheeseDogg0** [ScavStation/ScavStation#415]
#### Description of issue

Kelotane was replaced with synthskin, yet the pills are still called kelotane

#### Difference between expected and actual behavior
synthskin is synthskin, dammit

#### Steps to reproduce

look at the orange pills LOOK AT THEM

#### Specific information for locating
in med in pill bottles

#### Length of time in which bug has been known to occur
a while, prob since chem rewrite

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
There are no hits in the codebase for kelotane, I cannot see any reason for pills to be named this. It might have been someone naming them inround. Please reopen with a screenshot or something.
