### ISSUE TITLE
baxxid are avid readers and can't put a book down

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#417]
#### Description of issue
https://discordapp.com/channels/363422397648601108/663522358362898442/682926558759092366

@SodiumShine 
#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by SodiumShine** [comment]
Waiting on NebulaSS13/Nebula#59 before I do this one.

**Comment by MistakeNot4892** [comment]
Fixed in https://github.com/NebulaSS13/Nebula/pull/2348
