### ISSUE TITLE
Cleaning robot Rex cannot drop dragged items

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#437]
#### Description of issue
As sweeper rex, I can drag things by cntrl+clicking them. I cannot un drag them, locking me to haul them about for eterninty. Or until someone saves me.

#### Difference between expected and actual behavior
Re-clicking the object should remove it from my grasp. Or somthing.

#### Steps to reproduce

Be cleaning robot rex, Ctrl+click a lizard. Be tied to the lizard forever.

#### Specific information for locating

Cleaning robot rex, lizard.

#### Length of time in which bug has been known to occur

At least since today. Probably since drag rework

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
As discussed, you can use the Home key to drop needs more UI stuff but isn't technically a bug,
