### ISSUE TITLE
Airlocks broken [exodus]

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#441]
#### Description of issue
It appears that all lower-level airlocks and many non-solar airlocks are broken.  

#### Difference between expected and actual behavior
The airlock buttons don't appear to be tied to the airlocks themselves.

#### Steps to reproduce
push a button.  Are you satisfied?  If so, you pushed the wrong button.

#### Specific information for locating

maintenance tunnels

#### Length of time in which bug has been known to occur

Opening day

#### Client version, Server revision & Game ID

Server revision as of day exodus opened

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Buttons are fine, it's frequency not being set on the doors due to the wrong subtype being mapped.
