### ISSUE TITLE
Long airlock misaligned with its icon. [exodus]

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#442]
#### Description of issue
Dear people resources.  I'm loving the new medical bay.  There are some oddities, however.

Not only does every clown, dog, and child have access to this incomprehensibly large medical bay, but the large west door is a phantasm.  Or, the space gods have forgotten which way it was installed while they played with our lives.  Or... something.

Please see how I phase right through the door.
![West medbay entrance 01](https://user-images.githubusercontent.com/59771903/78466364-e45a9d00-76c5-11ea-8395-4556ef26df07.png)

And here, I found a ghostly connection to the door.  I couldn't reach out and touch it, but I COULD activate that giant airlock by approaching it.  It was not so on the other side.  

![West medbay entrance 02](https://user-images.githubusercontent.com/59771903/78466380-0ce29700-76c6-11ea-92d1-bdeffa94176c.png)

Or, perhaps, is it possible that I'm SO welcome that no closed door in my clinic is truly closed to me?  I'm unclear on the details.

#### Difference between expected and actual behavior
Airlocks ideally keep you out if they're closed.  I'm not even sure this thing keeps air separated from hallway to the whole of the medical bay.

#### Steps to reproduce
Approach the large west medbay door from the northern side.  It's not pretty.

#### Specific information for locating

Bring a ghost hunter and then go wild.

#### Length of time in which bug has been known to occur

Opening day

#### Client version, Server revision & Game ID

Server revision of opening day.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Closing these for now as Exodus isn't testmerged anymore - will revisit if I pick it up again, probably on Nebula side.
