### ISSUE TITLE
Escape procedures are busted (NSS Exodus)

### ISSUE THREAD

**Issue by Morguemeat** [ScavStation/ScavStation#443]
#### Description of issue

When the shuttle is called, it arrives just fine, but fails to open the airlocks to let anyone on board. Same with the escape pods. When the shuttle leaves, it claims that it will arrive at its destination in a large negative number of minutes, and then proceeds to count down from 40 minutes or so.

[https://i.imgur.com/II7CyZK.png](url)

#### Difference between expected and actual behavior

The Transfer/Escape Shuttle and Escape pods usually let people on them and take them away to the proper destinations in a timely manner.

#### Steps to reproduce

Initiate a crew transfer, or call the escape shuttle.

#### Specific information for locating

Escape Shuttle, Escape Pods.

#### Length of time in which bug has been known to occur

4/4/2020 -->

#### Client version, Server revision & Game ID

513
0e5d9c42e1f0a6e92ee7c261f11eee2198561067 - exodustest - 2020-04-05
b6w-avoD

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Morguemeat** [comment]
This apparently extends to the Supply shuttle as well.

**Comment by MistakeNot4892** [comment]
Closing these for now as Exodus isn't testmerged anymore - will revisit if I pick it up again, probably on Nebula side.
