### ISSUE TITLE
Overmap Pods Can't Redock (NSS Exodus)

### ISSUE THREAD

**Issue by Morguemeat** [ScavStation/ScavStation#444]
#### Description of issue

The overmap capable pods for the Exodus, once undocked, cannot redock with the station. One can only park them in various station approach locations, requiring the occupant(s) to spacewalk to a functioning external airlock to gain access to the station. 

#### Difference between expected and actual behavior

They really should be able to redock with the station so that they can recharge their SMES and allow occupants to safely and easily reboard.

#### Steps to reproduce

Get in one of the Overmap pods, undock, then attempt to return to the station.

#### Specific information for locating

Exodus Engineering Pod, Exodus Mining Pod, Exodus Research Pod.

#### Length of time in which bug has been known to occur

4/4/2020 -->

#### Client version, Server revision & Game ID

513
0e5d9c42e1f0a6e92ee7c261f11eee2198561067 - exodustest - 2020-04-06
b6x-cq6o

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Fixed on Neb exodus branch (hooray).
