### ISSUE TITLE
Security Cameras Do Not Work (NSS Exodus)

### ISSUE THREAD

**Issue by Morguemeat** [ScavStation/ScavStation#445]
#### Description of issue

What it says on the tin. While cameras exist in physical form all across the ship, not a one shows up on the Security Cameras program interface.

#### Difference between expected and actual behavior

Normally there would be a rather sizable populated list of cameras to work with when using the Security Cameras program.

#### Steps to reproduce

Use the Security Cameras program.

#### Specific information for locating

Security Cameras?

#### Length of time in which bug has been known to occur

4/4/2020 -->

#### Client version, Server revision & Game ID

513
0e5d9c42e1f0a6e92ee7c261f11eee2198561067 - exodustest - 2020-04-06
b6x-cZN0

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
should be fixed as of most recent merge.
