### ISSUE TITLE
Downstairs airlock issue

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#448]
#### Description of issue
Airlock works as intended, all except interior call button.  The inside airlock controls work, and the exterior call button works, too.  

This is the airlock just east of atmospherics, across from the elevator shaft.

#### Difference between expected and actual behavior
Interior call button doesn't open the door

#### Steps to reproduce
push a button

#### Specific information for locating

east of atmospherics, located in a button

#### Length of time in which bug has been known to occur

indefinitely, since the dawn of time

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by SodiumShine** [comment]
Which map?

**Comment by MistakeNot4892** [comment]
Tradeship airlock doesn't appear to have an interior button. Zirc'll need to add more info if they reopen this one.
