### ISSUE TITLE
Gloves prevent doing most things in and with hands.

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#449]
#### Description of issue
Wearing gloves breaks a lot of things. Such as bashing monkeys with a fire extinguisher, Grabbing monkeys, picking monkeys up, and more.

You can still punch em empty handed tho, so no uprisings anytime soon.

#### Difference between expected and actual behavior
Gloves should enhance one's ability to preform action without getting one's hands dirty. Not negate it entirely. Being unable to manipulate the monkey, or bring tools to bear against the monkey is out of line

#### Steps to reproduce
Go to Xeno Bio, and grab a monkey, and a set of Nitril gloves from the table. Make cube into monkey. Bash it over the head a few times with a fire extinguisher for easier manipulation.
Observe that you can do this. Pick it up, drag it, throw it around. Now put on the gloves, and try all this again. You won't. Because you can't.

#### Specific information for locating

Gloves

#### Length of time in which bug has been known to occur

Since the start of this patch?

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
This is very weird, might be a Neb issue. Will see if I can reproduce on clean Neb dev.

**Comment by AnotherGrunt** [comment]
All full body suits that I've tested so far share this issue.  This is despite some covering the hands but _not_ explicitly occupying the gloves slot.
This issue also extends to things that you can normally do with your hands full, such as opening all access doors.  This occurs even when passively walking through.  If I remember correctly, this should occur without hands (baxids can use all access doors)
Additionally, actions can still be performed through the right click menu when this glitch is in effect.  (example: Have gloves/suit on.  Cannot pick a object up with LMB.  Can pick up object using RMB>Pick up)

**Comment by AnotherGrunt** [comment]
You can also check off the "reproduced through multiple rounds" box.

**Comment by AnotherGrunt** [comment]
Click/Drag interactions still work.  The interact hotkey (Y) still works with held items.  Everything except LMB and passive interaction seems to still work with gloves on
