### ISSUE TITLE
Station Airlock Access is Incorrect (NSS Exodus)

### ISSUE THREAD

**Issue by Morguemeat** [ScavStation/ScavStation#450]
#### Description of issue

The majority of the airlocks on the Exodus have the incorrect access assigned to them. The following are areas I could simply walk into as an Assistant.

All of EVA
All of Command (Except Command Substation)
Teleporter
Bar Counter
Bar Backroom
All of Medical (Except Virology)
Kitchen
Kitchen Cold Room
Mech Bay
Robotics
Private Study
All of Cargo/Mining
Tech Storage
All of Engineering
Solars
Messaging Server
Cyborg Station

Also, I couldn't enter the Security Lobby as an Assistant.

#### Difference between expected and actual behavior

An Assistant shouldn't be allowed into any of those areas with their default access, but an Assistant definitely should be allowed into the Security Lobby so they can report CRIMES.

#### Steps to reproduce

Join a round on the Exodus map as an Assistant.

#### Specific information for locating

Airlock Access.

#### Length of time in which bug has been known to occur

4/4/2020 -->

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: b3bdbaa2e78d0cf28c4f214bd936e1777a0ef6bb - exodustest - 2020-04-15
Game ID: b6G-aKXJ

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Morguemeat** [comment]
Further testing has revealed the following airlocks have the incorrect Access as well.

Internal Affairs
R&D
Toxins Lab
Toxins Storage
Server Room
Research Director
Security Wing
Detective
Head of Security
Warden's Office
Armoury
Secure Armoury

**Comment by Morguemeat** [comment]
More testing and more discoveries. 

Solely having Holding Cells access will get you through every airlock in Security, save a few, so that's not right. 

Only having Maintenance access will get you through Atmos no problem.

Telecomms has no access set to its Airlock.

It honestly seems like every single airlock on the station that requires access at all has the wrong access set. Oof.

**Comment by MistakeNot4892** [comment]
Closing these for now as Exodus isn't testmerged anymore - will revisit if I pick it up again, probably on Nebula side.
