### ISSUE TITLE
dough disappears when produced?

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#454]
#### Description of issue
mixing dough yields air.  the materials vaporize.

#### Difference between expected and actual behavior
very odd.  Ghost bread probably makes for some really tasty ghost food, but corporeals gotta eat too, and since all the components are corporeal, this should be our food.

#### Steps to reproduce
mix egg, flour, and water.  Receive notification that dough has been mixed.  View total and complete absence of dough.

#### Specific information for locating

in a kitchen, more often than not

#### Length of time in which bug has been known to occur

today only, 4/17/2020, though I don't cook and hadn't attempted to make dough until today.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: c7936d04a5fcdc0ab7a46752efd1afbf0dde40d9 - exodustest - 2020-04-18
Game ID: b6J-akl8

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Fixed in last Neb pull.
