### ISSUE TITLE
captain on tradeship has no access

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#456]
#### Description of issue
I thought it was a little funny when I couldn't access my quarters after cryo-sleeping in, a decent way through my shift.  'Ha ha', I thought, 'Some crewman really got me this time.'  Then, I thought it was kinda cute that someone had locked me out of engineering.  'Ha ha', I mused, 'Some engineer is totally fired for rewiring all these doors.'  Then I found I was locked out of medical bay's health monitor console.  I was not alone, I had my radio on my person, but now I was REALLY thinking hard.  I know I haven't been the best captain you've ever had, but if you're gonna fire me and erase all my access credentials, I'm gonna need you to actually tell me.

-Presumed Captain Hailey McGee

#### Difference between expected and actual behavior
Doors and consoles do not recognize my authority as captain.  One expects the ship to respond to my authority... you know, as captain?  Unless I'm not captain anymore.

#### Steps to reproduce
Use my Captain's ID.  I mean, shit.  The scav's even got the spare ID, and that works.  Just mine?  That's a tough pill to swallow, Ivenmoth.

#### Specific information for locating

ID of a captain.  Possibly other ranking officials?  I'm not sure.  but this is bullshit, Ivenmoth.  I'm getting angrier as I write, and I didn't think that possible, because I was pretty angry to begin with.

#### Length of time in which bug has been known to occur

Just today.  4/30/2020.  

#### Client version, Server revision & Game ID

Server Revision: c7936d04a5fcdc0ab7a46752efd1afbf0dde40d9 - exodustest - 2020-04-30
Game ID: b6V-c2Oo
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by AnotherGrunt** [comment]
Addendum:
Literally no one has access by default
Not the captain, not the scavs.
If anything get's done, it must be because the spare ID was located and used to restore clearance

**Comment by AnotherGrunt** [comment]
If I select a role to give with the ID card modification software, it gives the proper, working permissions.
Moreover, the cards we have **do** have our role, but seem to lack the associated permissions unless fixed using the terminal
