### ISSUE TITLE
Ore processor issue on tradeship; inoperable conveyor is preventing use

### ISSUE THREAD

**Issue by AnotherGrunt** [ScavStation/ScavStation#457]
#### Description of issue
Look at the mineral processor in the loading bay, then look at the tiles north of that.  There is a conveyor belt here, which is presumably present to make it impossible to put anything in the mineral processor without using the unloader and the ore box. 
These conveyors are not moving, and by design they are inaccessible.  This makes it impossible to use the mineral processor using the intended means.

#### Difference between expected and actual behavior
The conveyor belts are not moving, and I can find no way to start them.  Presumably these should either be active at start, or activated by button

#### Steps to reproduce
Present at start of map.  Simply go to the loading bay, and look at the north side.

#### Specific information for locating

Deck 2, loading bay, north.  The three conveyors north of the unloader and the mineral processor are static.

#### Length of time in which bug has been known to occur

Weeks, if not months.  As long as I can remember

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: c7936d04a5fcdc0ab7a46752efd1afbf0dde40d9 - exodustest - 2020-05-01
Game ID: b6W-adTx
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by SodiumShine** [comment]
![image](https://user-images.githubusercontent.com/4461697/81056115-4f89d000-8f0d-11ea-8f3f-62da658a82e3.png)
This lever should make the belt move. Just tested it and works fine for me.

**Comment by AnotherGrunt** [comment]
Ah, my bad
