### ISSUE TITLE
The mineral processor will leave a full 'corpse' that is missing all bodyparts

### ISSUE THREAD

**Issue by AnotherGrunt** [ScavStation/ScavStation#458]
#### Description of issue
When someone is killed by the mineral processor (furnace in loading bay) they leave a corpse with no body parts remaining, that still is fully visible, and looks to have a head, body, and some other stuff.  You can look at it, examine, check it's pulse, try to loot (though nothing on them)

#### Difference between expected and actual behavior
There is a 'corpse' that you can interact with, despite there being nothing left of the body

#### Steps to reproduce
Die by being in the input tile to the mineral processor.  Respawn and examine the corpse

#### Specific information for locating

Mineral processor, top left of loading bay

#### Length of time in which bug has been known to occur

Unknown, there was a possible similar incident weeks ago, where the corpse remained

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: c7936d04a5fcdc0ab7a46752efd1afbf0dde40d9 - exodustest - 2020-05-01
Game ID: b6W-adTx
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by SodiumShine** [comment]
Related to #341

**Comment by MistakeNot4892** [comment]
No longer an issue post mining rewrite.
