### ISSUE TITLE
low priority: sedative quandry

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#462]
#### Description of issue
I sugared my medical grade ethanol as a sleep-aid and all I got was drunk!  Requesting tradehouse chemists to re-examine a tried-and-true sedative formula and let me know what I'm doing wrong!

#### Difference between expected and actual behavior
I drank a bit and it was just sweet booze!  And not GOOD sweet booze!

#### Steps to reproduce
Mix alcohol and sugar!  And drink!  Or inject!

#### Specific information for locating

Local chemistry lab

#### Length of time in which bug has been known to occur

Today only

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 40ef144a5c3ac9f519b8171d584ec043e89458fe - dev - 2020-05-05
Game ID: b61-aktL
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by SodiumShine** [comment]
Actually unsure what the issue is about to be honest.

**Comment by MistakeNot4892** [comment]
Not a bug, but an oversight - reagent types are rigidly defined now and /ethanol does not exist ingame. I've added a way to boil other alcohol down to pure ethanol for the purposes of this recipe in the most recent Nebula PR.

**Comment by MistakeNot4892** [comment]
I was wrong, not fixed.

**Comment by MistakeNot4892** [comment]
Fixed properly in most recent Nebula pull.
