### ISSUE TITLE
Minor animation bug of seed vendor

### ISSUE THREAD

**Issue by sharah-za-fluffy** [ScavStation/ScavStation#471]
#### Description of issue
machine turns invisible while vending seeds 

#### Difference between expected and actual behavior
it is not the proper animation if any for it 

#### Steps to reproduce
vend any seed packet from it

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
This is a strange one, I can reproduce it easily on Tradeship but the icon states seem to be present in the appropriate icon.

**Comment by MistakeNot4892** [comment]
Fixed upstream https://github.com/NebulaSS13/Nebula/pull/2350
