### ISSUE TITLE
(ministation) pet slime research 

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#473]
#### Description of issue
Dear People Resources

Researcher Izzna here again.  I went into the xenobiology lab for entirely wholesome and research oriented purposes.  During my time in the laboratory, I discovered something hilarious.  Whoever you left in charge of xenobio last time was a CHILD.  They've filled the secure slime storage with inert slime pets.  These things are great for researching effects on mood a good pet has.  Or what the surface tension of inert slime is.  What they don't do, however, is progress the field of real science in the least.  

This is my formal recommendation:  Fire my predecessor.  Outright and without warning.  I don't know how many months of pay they collected, working on inert, worthless slime. 

-Researcher Izzna

#### Difference between expected and actual behavior

Slime should DIE upon being sprayed with a fire extinguisher.  Oh, and uh.  It should furthermore be something you can actually research.  and learn from, I suppose.This stuff is, as mentioned, inert as far as expected biochemical reactions are concerned. 

#### Steps to reproduce

feed the slimes a monkey.  Feed them a cadaver.  Feed them whatever you like.  They're not hungry for flesh like the useful slimes are.

#### Specific information for locating

Xenobiology lab.  DO try to keep up, now.

#### Length of time in which bug has been known to occur

Since ministation's grand re-opening

#### Client version, Server revision & Game ID

Any version, map issue

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Wrong mob type was used, these are the passive pet slimes you get from the slime potion.
