### ISSUE TITLE
Indrel Val-confirmed list

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#477]
~~+Voidtight~~ Done, thanks Alceris.
+ Natural armour
+Crushy grip
+make window, windoor, and floor out of 'pulp'
+ make sticky resin for sealing suits/duct tape replacement
+Extra leaping distance/speed/frequency
+maybe climb if port can be assed.
+maybe safely crawl disposals
+ Claw toggle between digging and dig
= Scent
- Basically no clothes
- speaking is hard.
? Darkvision (Canonically thermals, non-viable till that's reworked)
? Bonding (Indrel making the ship considered their new hive. maybe only crew is considered hivemates)

**Comment by TheKnightofAura** [comment]
ps. Fuck formatting

**Comment by MistakeNot4892** [comment]
Going to close this off similarly to the alchemy issue as it's unlikely to be implemented in the short term.
