### ISSUE TITLE
[ministation] Something wrong with servers

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#480]
#### Description of issue
Dear Informational Technicians of Tradehouse Ivenmoth, Remote Services and Tech Hotline Representitives Division,

I am writing today because our servers are down here on the remote Tradehouse Ministation Zebra (You know, the dogsbody of a station no one wants to be assigned to).  Yes, the servers ARE plugged in.  Yes, they started faulty at the start of each shift for who knows how long.  No, I don't know if the janitor used the servers to shop for new mops and mistakenly downloaded a virus.  This isn't my job, it's yours, and if these servers are any indication, you should want for new employment in the very near future.  Shouldn't the lack of server communication have been some kind of indication that the station had problems?  Shame on you, you have no idea the degree to which this has inhibited my research at every turn.

-Researcher Izzna

Senior Behavioral Studies Researcher
Tradestation Miniature Zebra
Department of furthering the medical sciences through any means necessary
Izz.brainscanner@tradehouseivenmoth.net 

#### Difference between expected and actual behavior
Servers are expected to fail daily, so really, there's no difference - but that's not desirable. 

#### Steps to reproduce
1) clock in for a shift.  
2) Check your PDA for server connection 
3) despair

#### Specific information for locating

any device that uses networking to function (On ministation)

#### Length of time in which bug has been known to occur

About a week?  Or so?  I can't be bothered to pay attention to such things, it's beneath me.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: cd2e346166c9e278c0174e716130b675fd605f9e - dev - 2020-05-24
Game ID: b7j-dshf
Current map: Ministation Zebra

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by SodiumShine** [comment]
Should be fixed in #481
