### ISSUE TITLE
Tradeship shuttle airlock woes

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#486]
#### Description of issue
Tradeship shuttle airlocks failing to work, might be something I can fix with coaching.  We'll have to see.  Also, only tested this once, repeat tests needed to confirm mechanism failure

#### Difference between expected and actual behavior
Tradeship shuttle airlocks might open when button is pressed.  This did not happen until someone managed to raise the interior door's bolts.  Possibly, just the interior button is disconnected.

#### Steps to reproduce
Push interior button on tradeship while on exoplanet.  It doesn't go anywhere.
Land shuttle and push airlock release button.

#### Specific information for locating

tradeship shuttle

#### Length of time in which bug has been known to occur

Today only

#### Client version, Server revision & Game ID

version per 6/2/20

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by ZirconiumWit** [comment]
Tradeship shuttle airlocks still causing problems.  I see the ID tag mismatch issue was closed - Is this no longer the issue?

**Comment by MistakeNot4892** [comment]
There's a lot of potential issues with airlocks but I can't reproduce this on current dev. May have been a lack of power, an atmos imbalance, etc.
