### ISSUE TITLE
Matriarch/patriarch credentials revoked in tradeship

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#487]
#### Description of issue
scav-specific jobs don't seem to have access credentials built-in to jobs.  Matriarch spawned sans-robe and without PDA but DID have her headpiece.  Needs more testing tbh, only tried it once.

#### Difference between expected and actual behavior
fully clothed elite scavs are expected.  We did not get that.  Matriarch got a simple, sad loin cloth.  And, these jobs didn't get expected access credentials

#### Steps to reproduce
Spawn as matriarch or patriarch in tradeship.  check gear/ID.  

#### Specific information for locating

matriarch robes (not there), matriarch ID (lacks color), matriarch PDA (MIA)  Patriarch access, and unsure about other patriarch things missing

#### Length of time in which bug has been known to occur

today only (to my awareness)

#### Client version, Server revision & Game ID

as of 6/2/20

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Fixed in most recent Neb PR.
