### ISSUE TITLE
Robots can black out, and 'drop' deployed tools if leaped at

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#488]
Might need to be elevated to Nebula, but this happened on scav. Was playing as Roomba janitor, and yinglet leapt and collided with me. This caused my screen to black out, and when I came-to, my hotbar was empty as if I'd stored all my tools. (Exactly as if. I could pull em back out and use em as normal)
Health reading under status still read 100%, even after repeating several times, which blacked me out each time.

**Comment by MistakeNot4892** [comment]
This isn't actually a bug, it's due to tackling calling Weaken(). Can be revisted if it isn't desirable but seems pretty much what you'd expect from a tackle, since it makes humans fall over and drop their gear and you can't prone a robot.
