### ISSUE TITLE
Server won't restart

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#494]
#### Description of issue
Server claims it's restarting but waiting for server updates, and just sits static as if it's updating, seemingly perpetually.  Admin commands to restart do cause it to announce shutdown procedures but the world remains open and nonfunctional (water physics seem to have halted due to shutdown initiation, for example).  I'm going to let it idle for a while, it's been about half an hour, maybe more as I write this.   Will delete ticket if erroneous/issue corrects itself/it's ACTUALLY just taking a long time to update.

#### Difference between expected and actual behavior
Expected: Server restarts when restart is initiated
actual: Server does nothing of the sort

#### Steps to reproduce
attempt to restart server, observe behavior

#### Specific information for locating

byond://enclave.lohikar.io:9001

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 49687b99e2f79a4dd8a2030538ec9e5dff91a902 - dev - 2020-06-19
Game ID: b7J-dFWg
Current map: Tradeship Ivenmoth

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
This seems to be a problem with the actual server rather than the scripts (possibly a new version of Git causing problems). Will leave it open but mark it as not a code bug.

**Comment by MistakeNot4892** [comment]
Misclick oops

**Comment by MistakeNot4892** [comment]
Moved upstream.
