### ISSUE TITLE
seemingly useless Ripley drill 

### ISSUE THREAD

**Issue by sharah-za-fluffy** [ScavStation/ScavStation#497]
#### Description of issue
drill don't seem to do much if any damage to walls like the reinforced glass of the shuttle's airlock and seems to fail to hit mobs like megaleeches

#### Difference between expected and actual behavior
said walls and megaleeches not suffering a sudden lack of existence when hit by drill

#### Steps to reproduce
use drill on things and be dissapointed at the lack of meaningful damage

#### Specific information for locating

the ripley suit on bearcat/tradeship and it's shuttle, ask dessi to find you a leech infested planet, she's a bit of a savant at that 

#### Length of time in which bug has been known to occur
since the one and only time I actually brought the ripley to a exoplanet, two days ago I think

#### Client version, Server revision & Game ID

I need to actually use that verb

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Can't reproduce most of this, the drill kills leeches in one hit and goes through walls and flooring.
Keep in mind it isn't a weapon, you need to hold still and channel for a bit before it will do any damage.
There is a bug with window explosion_act preventing it from taking any damage currently which I'll fix on Neb.
