### ISSUE TITLE
Suit Cyclers locked

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#500]
#### Description of issue
Regardless of what kind of access you're flaunting, suit cyclers remain locked.  Seems like you have to pull them apart to get the suits out of them.  

A note:  This MIGHT be specific to the tradeship.  I'm not sure.  I'm posting here first, 

#### Difference between expected and actual behavior
Ideally, you don't have to tear apart expensive, sensitive equipment to go exploring.  

Ideally, you only have to tear expensive, sensitive equipment apart because you feel upset with your captain and don't know how else to get back at the man.

#### Steps to reproduce
find a planet.  declare approach to orbit, order crew to prepare to go on expedition.  Listen to radio for complaints about suit cyclers not working.

#### Specific information for locating

/obj/machinery/suit_cycler/tradeship

#### Length of time in which bug has been known to occur

Unsure.  It's been going for a bit, but engineering/EVA isn't really my area.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 9e31062250422a862959ff2c29d8e6e5afeb11e9 - dev - 2020-07-19
Game ID: b8d-bmoa
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed in #513.
