### ISSUE TITLE
Robco Tool Maker locked

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#501]
#### Description of issue
Similar to #500 , but unable to verify same-issue.  Robco Tool Maker does not accept access credentials of any level.

#### Difference between expected and actual behavior
Secure vending machine is secure, this actually sounds ideal.

#### Steps to reproduce
Approach Robco Tool Maker and feel it watching you.  Select a product, only to realize that the machine simply won't cooperate with you unless you hack it.

#### Specific information for locating

/obj/machinery/vending/engineering

#### Length of time in which bug has been known to occur

A bit.  Unsure, engineering's not my area.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 9e31062250422a862959ff2c29d8e6e5afeb11e9 - dev - 2020-07-19
Game ID: b8d-bmoa
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Fixed in #513.
