### ISSUE TITLE
Enclave deck has no signal

### ISSUE THREAD

**Issue by Greenjoe12345** [ScavStation/ScavStation#511]
#### Description of issue
when you go down into the enclave's deck, on the bottom of the tradeship, your PDA, and I'd guess other devices, lose their signal

#### Difference between expected and actual behavior
for my PDA to not lose signal on the bottom deck

#### Steps to reproduce
use a PDA on the enclave's deck

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Fixed in #513.
