### ISSUE TITLE
mapping error with external blast doors, utility issues

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#516]
#### Description of issue
![image](https://user-images.githubusercontent.com/59771903/91628228-5d170a00-e983-11ea-9cfd-b77779cf3fd5.png)
For documentation purposes, this is going here.  Might be a pretty good starter mapping issue if someone's looking to get into mapping wink wink nudge nudge say no more

#### Difference between expected and actual behavior
external windows should be covered by blast doors when blast doors are shut

#### Steps to reproduce
Shut blast doors, witness space and despair

#### Specific information for locating

tradeship

#### Length of time in which bug has been known to occur

Today only

#### Client version, Server revision & Game ID

current game version as of 8/28/20, sorry, didn't get that

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Fixed upstream.
