### ISSUE TITLE
Shuttle airlock internal button busted still

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#517]
#### Description of issue
Can't open the interior airlock door with the interior airlock button.  Door works fine with controls inside the airlock, so it's a matching error or something?

#### Difference between expected and actual behavior
airlocks are nice to open by button and not by admin nonsense or hacking.

#### Steps to reproduce
Try to open the interior airlock hatch in the shuttle.  You'll have to detach the shuttle from the ship to do so.

#### Specific information for locating

???

#### Length of time in which bug has been known to occur

few weeks

#### Client version, Server revision & Game ID

current ver as of 8/30/20

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by SodiumShine** [comment]
No map specified, but I assume tradeship. Is this related to #486 ?

**Comment by MistakeNot4892** [comment]
There's a lot of potential issues with airlocks but I can't reproduce this on current dev. May have been a lack of power, an atmos imbalance, etc.
