### ISSUE TITLE
note to self- add scav tradecoats to matriarch's locker, add human tradecoats to closet in first mate's chamber

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#521]
#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Going to close this as Zirc isn't around currently.
