### ISSUE TITLE
Ministation cargo shuttle won't disembark from ministation

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#523]
#### Description of issue
Cargo shuttle can be filled and ordered to arrive, and will successfully deliver goods, but will not return to old station.

#### Difference between expected and actual behavior
Cargo shuttle comes and goes as job mandates

#### Steps to reproduce
order some stuff, and call the shuttle in. Remove everything, and send shuttle back

#### Length of time in which bug has been known to occur

since ministation update

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by ZirconiumWit** [comment]
notes to self- shuttle initializes at offsite apparently, does not spawn from thin air.

**Comment by MistakeNot4892** [comment]
This is being looked at on Neb currently, might be fixed in the near future.

**Comment by MistakeNot4892** [comment]
Fixed on current dev.
