### ISSUE TITLE
Junior scientists cant access R&D on the tradeship

### ISSUE THREAD

**Issue by Recon104** [ScavStation/ScavStation#524]
#### Description of issue
Junior scientists are unable to open any of the doors to R&D on the tradeship. 

#### Difference between expected and actual behavior
They should have access to the doors as per the scientist job.

#### Steps to reproduce
Join as R&D, attempt to open door.

#### Length of time in which bug has been known to occur

Few weeks.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Fixed by https://github.com/NebulaSS13/Nebula/pull/885
