### ISSUE TITLE
Engineering access to front storage on tradeship

### ISSUE THREAD

**Issue by Qumefox** [ScavStation/ScavStation#525]
#### Description of issue

Only command has access to this storage, meaning engineers have to break in every round

#### Difference between expected and actual behavior

This is an engineering area. Engineering should have access.

#### Steps to reproduce

Be an engineer. try to get to the hydrogen canister or forward shield generator.

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Fixed by https://github.com/NebulaSS13/Nebula/pull/885
