### ISSUE TITLE
ATM access on tradeship

### ISSUE THREAD

**Issue by Qumefox** [ScavStation/ScavStation#526]
#### Description of issue

The ATM on tradeship is locked behind a command only door.  The rest of the crew can't access it without shenanigans. ATM should either be moved to an accessible location or the hatch leading to it should be made all access.

#### Steps to reproduce

Try to get to the ATM as a non-command role. 

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Greenjoe12345** [comment]
Yeah this became an issue after the Tradeship enhancement

**Comment by MistakeNot4892** [comment]
Fixed by https://github.com/NebulaSS13/Nebula/pull/885
