### ISSUE TITLE
error compilation

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#529]
~~Welding masks no-longer visually flip up and down~~
~~engineering secure voidsuit locker no-longer openable by jr Engineer~~
Will comment addition as they arrive

**Comment by TheKnightofAura** [comment]
Zmimic blood didn't clear when blood below was cleared: Attempting to clear zmimic blood only returns 'Blood is too far away'

**Comment by TheKnightofAura** [comment]
Sal Valia calms down about 10 times a second

**Comment by TheKnightofAura** [comment]
Blood transfer still seems to cause organ failure, even if right type is used?

**Comment by TheKnightofAura** [comment]
Drinks still overpriced

**Comment by TheKnightofAura** [comment]
No crew survival kits?

**Comment by TheKnightofAura** [comment]
Slime has door access

**Comment by TheKnightofAura** [comment]
Indrel Autohiss only on 'Basic' not 'full'
Indrel don't have method of laying scents yet?

**Comment by MistakeNot4892** [comment]
`Drinks still overpriced` - somewhat fixed on Neb main, there was a crippling bug with prices. They're still pretty steep (300cr a can or so) but much less than before.
Indrel are able to lay pheromones currently.
What would 'full' Indrel autohiss look like?
What is Sal Valia? Can't find a reference in the code.

**Comment by MistakeNot4892** [comment]
Welding helmet flip - only doesn't work for scavs, unsure why, will look into it.

**Comment by TheKnightofAura** [comment]
It's been many a moon, so my memory is a little foggy, but I believe Sal Valia was a parrot we had at one point, perhaps via adminspawn?

And if I remember correctly, my comment about full autohiss was because 'full' was acting like 'no'

**Comment by MistakeNot4892** [comment]
- Parrot bug has been upstreamed.
- Indred autohiss works on Full, does not work on Basic.
- Bunch of other stuff has been checked and appears to have been resolved in the last year.
