### ISSUE TITLE
Welding masks no-longer flip up and down visually for yinglets

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#530]
#### Description of issue
Welding masks no-longer flip up and down visually

#### Difference between expected and actual behavior
masks visually flip up and down as they actuially are

#### Steps to reproduce

be a yinglet, wear a welding mask, and click the toggle button top-left. Notice on your icon that nothing changes, but the mask is flipped properly in practice, allowing you to burn out your eyes, or eat pills

#### Specific information for locating

knightly welding mask, onna yinglet

#### Length of time in which bug has been known to occur

very recently

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Should be fixed as of Neb update - please reopen upstream if it persists.
