### ISSUE TITLE
Jr. Engineer can't access secure engineer suit locker

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#531]
#### Description of issue

Jr. Engineer can't access secure engineer suit locker after last access updates

#### Difference between expected and actual behavior
Jr engineer, being an engineer, can get into the locker holding engineer suits

#### Steps to reproduce

be a Jr.Engineer, and try to open the secure suit locker, in need of the suit, and be turned away wanting.

#### Specific information for locating

suit locker under engineering

#### Length of time in which bug has been known to occur

since access updates

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
For some reason the voidsuit locker is restricted to Chief Engineer access specifically. Quite odd.
