### ISSUE TITLE
Missing Blood Type

### ISSUE THREAD

**Issue by Qumefox** [ScavStation/ScavStation#561]
#### Description of issue
Blood type O- is missing

#### Difference between expected and actual behavior
When creating a character. O- is not on the list of blood types and it should be.

#### Steps to reproduce

Create or edit a save slot and try to choose O- as a blood type

#### Length of time in which bug has been known to occur

First noticed on 5/7/22

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 51899e22282a1c66035e59ab4a88bd4524b97ab0 - dev - 2022-05-07
Game ID: chO-dMr9
Current map: Tradeship Ivenmoth

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Fixed upstream https://github.com/NebulaSS13/Nebula/pull/2345
