### ISSUE TITLE
Surgery broke?

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#564]
#### Description of issue
Doctor's log, stardate...  Can't find my calendar.  Too lazy to bring up my PDA.  Don't know the date.  Doesn't matter much.

My eyes filled with red when performing surgery today.  It's been a while.  However, I've never experienced a bloodlust of this variety before.  Central organs?  Fine, I can crack open a ribcage and fix your lungs.  It would be my pleasure.  Your ARMS, though.  As soon as I opened up my patient's arms to begin bone repairs, I was filled with a foreign and terrifying emotion.  I had no interest in continuing the surgery, I could not bring myself to clamp the  bleeders or retract the surgical incision.  No, instead, I felt a damning desire to continue making additional and unnecessary incisions.  I likely could have continued making incisions all day, but the nosy crew would mercifully continue to come and go like mad animals, never leaving me a moment's peace - and this was for the best, as I decided to stitch the victimpatient closed again and simply slap a set of splints on the shattered limb.  

Perhaps this is that space madness I've read about?  

-Dessili

#### Difference between expected and actual behavior
Well.  Truth be told, now that I'm out of the moment, I'm unsure about this one.  Ideally, a doctor would use surgery to heal.  However, we do not live in an ideal universe.  But, I suppose it remains expected that a doctor at least ATTEMPT to make repairs once they've sliced a patient open.

#### Steps to reproduce
Put a patient on the table.  Begin the butchery with your scalpel.  continue the butchery until desired results are achieved.  seems to only effect limbs, though.  central body seems to work as expected.

#### Specific information for locating

yinglets, maybe?  I only operated on yinglets.  the monkey I uncubed did not elicit the bloodlust.

#### Length of time in which bug has been known to occur

today only?

#### Client version, Server revision & Game ID

most recent ver as of 5/13/22

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
Someday we need to compile all of your bug reports in a thread.

This has been fixed upstream.
