### ISSUE TITLE
Phantom limb pain after fighting spacecarp? 

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/ScavStation#584]
#### Description of issue
I play a one-armed character, and I started having odd aches and pains in the missing limb after fighting a space carp, as per image below.  You can clearly see absence of limb as well as pain prompt.  
![image](https://user-images.githubusercontent.com/59771903/181870847-3a02ffd2-3c7c-42a0-807a-90afe416b151.png)

#### Difference between expected and actual behavior
Unsure!  Is this an effect of space carp venom?  If so, then there is no difference.  If not, however, then probably should not happen?

#### Steps to reproduce
Unclear.  I chopped myself with a hatchet shortly before fighting the space carp, because clumsy.  hit my lower body.  unsure if that had an effect? 

#### Specific information for locating

Wish I knew more.  I was: Wearing a space suit with the oxygen on, had struck myself in the lower body with a hatchet while preparing to fight the carp, fought the carp with said hatchet, and then noticed pain prompts from phantom limb.  May not be replicable. May be a feature of carpotoxin.

#### Length of time in which bug has been known to occur

Short time player, first time experience.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 2639e97e005fb4508e1a1458b55611e219f5cf9f - dev - 2022-07-22
Game ID: cja-aGzV
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
This is actually an ailment rather than an effect of carp specifically. It should be possible for this to apply to a removed limb, since removed limbs should have been deleted. Very odd.

**Comment by MistakeNot4892** [comment]
Something's fucky with amputation aspects I think:
![image](https://user-images.githubusercontent.com/2468979/182354741-63cfa7d2-e29e-4941-b50f-bb40fc35c830.png)

**Comment by MistakeNot4892** [comment]
Should be fixed when Qume updates from Neb staging.

**Comment by Qumefox** [comment]
Fix merged. Closing
