### ISSUE TITLE
hydro tray bubbling loop and buggy fertalizer bottles

### ISSUE THREAD

**Issue by sharah-za-fluffy** [ScavStation/ScavStation#601]
#### Description of issue
constant bubbling of hydroponics trays and both fertilizer and trays reading as -nan units left 

#### Difference between expected and actual behavior
said buggy remaining units readout and constant annoying bubbling spam that can be heard from all decks 

#### Steps to reproduce
not sure but I belive it's this: 
1: let trays be drained fully of water and nutrients by weeds  
2:remove dead weeds but do not use hoe to weed out the tray further
3: using bucket set to 180 units fill with sink and then pour it into tray
4: take bottle of fertilizer and dump most if not all of it in tray
5: if bug happens it should read as -nan units in bottle and tray and the bubblepocalyce is apon you  

#### Specific information for locating

it contains -nan amounts of liquid

#### Length of time in which bug has been known to occur

happened first around noon of august 20th 2022

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: cfe491f97b99736add5bf046c7a3970b3fc8fc50 - dev - 2022-08-19
Game ID: cjv-buNB
Current map: Tradeship Ivenmoth

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by Qumefox** [comment]
This isn't a scav specific issue so I transferred it to the nebula issue tracker.  Going to close this copy.
