### ISSUE TITLE
Airless Plating in Library Door

### ISSUE THREAD

**Issue by LuchiousCaine** [ScavStation/ScavStation#770]
#### Description of issue
Last Friday round we found an airless plating in a library door. 
Although it didn't seem to cause any obvious issues during play, it could still cause some atmos issues if left there.

#### Difference between expected and actual behavior
There should a regular floor plating there.

#### Steps to reproduce
Simply go to the door seen in the attached screenshot.

#### Specific information for locating

Underneath the door between Librarian's personal room and the maint tunnel.

#### Length of time in which bug has been known to occur

A week, found 15th Sep.

#### Client version, Server revision & Game ID

Date 2023-09-21
Branch dev
Game ID cpU-bFop
Runtime Version 514.1589
Compiler Version 514.1589
Revision 5d86e62410a691f4860ff08ea218cc7fcdf191ca

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

![AirlessPlatingScav](https://github.com/ScavStation/ScavStation/assets/136999778/e7cfc4ae-e58c-4035-b44b-44ebec1af0e8)

**Comment by Qumefox** [comment]
Fixed on #771
